spring:
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 500
        one-indexed-parameters: true
        page-parameter: page
        size-parameter: size
management:
  endpoints:
    web:
      exposure:
        include: health,refresh,env,metrics,logfile,info
  server:
    port: 8081
---
spring:
  profiles: sql
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
    initialization-mode: embedded
  h2:
    console:
      enabled: true